import React from 'react';
import { Grid, Navbar, Panel, Row, Col, Button, ButtonToolbar } from 'react-bootstrap';
import AceEditor from 'react-ace';
import { connect } from 'react-redux';
import { getSource, getResult, edit, typecheck, share } from './editing';
import 'brace/theme/tomorrow_night_bright';

require("./mode-michelson.js")

const HeaderUnconnected = ({ typecheck, share, source }) => {
  return <div className="panel-heading clearfix">
    <ButtonToolbar>
      <Button bsStyle="primary" onClick={typecheck} disabled={source === ""}>Typecheck</Button>
      <Button bsStyle="info" onClick={share} disabled={source === ""}>Share</Button>
    </ButtonToolbar>
    </div>
}

const Header = connect(
  state => ({ source: getSource(state) }),
  { typecheck, share }
)(HeaderUnconnected)

const RenderPage = ({ source, edit, result }) => {
      return <div>
        <Navbar inverse staticTop>
          <Grid>
            <Navbar.Header>
              <Navbar.Brand>
                <a href="/">Try Michelson</a>
              </Navbar.Brand>
              <Navbar.Toggle />
            </Navbar.Header>
          </Grid>
        </Navbar>
        <Grid>
        <Row>
          <Col xs={12} md={5} className="col-md-push-7">
          <Panel header="Getting Started">
            <div style={{height: "330px"}}>
            <p>This is a tool to make it easy to try out Michelson, Tezos's low-level smart contract language. Type or paste in a Michelson contract and click "Typecheck" to check its validity and see a stacktrace (generated by a Tezos node running on the server).</p>
            <p>You can find example Michelson contracts on <a href="https://www.michelson-lang.com/">michelson-lang.com</a> and 
            in the <a href="https://github.com/tezos/tezos/tree/master/test/contracts">Tezos Github</a>.</p>
            <p>You can learn more about Michelson from the <a href="https://github.com/tezos/tezos/blob/master/src/proto/alpha/docs/language.md">docs</a>,
            or this <a href="https://www.youtube.com/watch?v=4oG4Ead74xA">video</a>.</p>
            <p>This demo is provided for convenience only. Do not rely on it for anything serious.</p><p>This project has no affiliation with the Tezos Foundation.</p>
            </div>
          </Panel>
          </Col>
          <Col xs={12} md={7} className="col-md-pull-5">
          <Panel header="Source">
              <AceEditor
              mode="michelson"
              theme="tomorrow_night_bright"
              name="codeEditor"
              width="100%"
              height="330px"
              value={source}
              onChange={edit}
              editorProps={{$blockScrolling: true}}
              setOptions={{useSoftTabs: true, wrap: true }}
            />
          </Panel>
          </Col>
        </Row>
        <Row>
        <Col xs={12}>
        <Panel header={<Header />}>
            { result && <pre>{ result }</pre> }
          </Panel>
          </Col>
        </Row>
        </Grid>
        <footer className="page-footer">
          <div className="container">
            created by <a href="https://twitter.com/danrobinson">@danrobinson</a>
          </div></footer>

      </div>}

const App = connect(
  (state => ({ source: getSource(state), 
               result: getResult(state) })),
  { edit }
)(RenderPage)

export default App;